workflows:
  ios-build:
    name: Reveil iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build Reveil
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/Reveil.xcodeproj" \
            --scheme "Reveil"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM